package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("tests_for_hhru")
    void generatedTest() {
        step("open https://ekaterinburg.hh.ru//vacancy/51857862?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=QA%20engineer%20java", () -> {
            step("// todo: just add selenium action");
        });

        step("check the correspondence of the job title to the expectation: Middle QA Engineer", () -> {
            step("// todo: just add selenium action");
        });

        step("check the compliance of the address with the vacancy: Екатеринбург, улица Ткачей, 23", () -> {
            step("// todo: just add selenium action");
        });

        step("check compliance in key skills Java", () -> {
            step("// todo: just add selenium action");
        });

        step("check compliance in key skills Jira", () -> {
            step("// todo: just add selenium action");
        });

        step("check compliance in key skills Selenide", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://ekaterinburg.hh.ru//vacancy/51857862?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=QA%20engineer%20java'", () ->
            open("https://ekaterinburg.hh.ru//vacancy/51857862?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=QA%20engineer%20java"));

        step("Page title should have text 'Вакансия Middle QA Engineer в Екатеринбурге, работа в компании СКБ ЛАБ'", () -> {
            String expectedTitle = "Вакансия Middle QA Engineer в Екатеринбурге, работа в компании СКБ ЛАБ";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://ekaterinburg.hh.ru//vacancy/51857862?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=QA%20engineer%20java'", () ->
            open("https://ekaterinburg.hh.ru//vacancy/51857862?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=QA%20engineer%20java"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}